name: CreateStringUpdatePR

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  CreateStringUpdatePR:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: write-all

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - id: get_access_token
        name: Get Access Token (API)
        env:
          GRANT_TYPE: ${{ secrets.BOX_GRANT_TYPE }}
          CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          BOX_SUBJECT_TYPE: ${{ secrets.BOX_SUBJECT_TYPE }}
          BOX_SUBJECT_ID: ${{ secrets.BOX_SUBJECT_ID }}
        run: |
          access_token=$(
            curl -s -X POST \
            -H "Content-Type:application/x-www-form-urlencoded" \
            -d "grant_type=${GRANT_TYPE}" \
            -d "client_id=${CLIENT_ID}" \
            -d "client_secret=${CLIENT_SECRET}" \
            -d "box_subject_type=${BOX_SUBJECT_TYPE}" \
            -d "box_subject_id=${BOX_SUBJECT_ID}" \
            'https://api.box.com/oauth2/token' | \
            jq -r ".access_token"
          )
          echo "::add-mask::${access_token}"
          echo "access_token=${access_token}" >> $GITHUB_OUTPUT  

      - id: get_target_directory_id
        name: Get target directory id (API)
        env:
          BOX_STRING_ROOT_DIRECTORY_ID: ${{ secrets.BOX_STRING_ROOT_DIRECTORY_ID }}
        run: |
          target_directory_id=$(
            curl -s -X GET \
            -H "Authorization:Bearer ${{ steps.get_access_token.outputs.access_token }}" \
            "https://api.box.com/2.0/folders/${BOX_STRING_ROOT_DIRECTORY_ID}/items?limit=1&sort=date&direction=DESC" | \
            jq -r ".entries[0].id"
          )
          echo "::add-mask::${target_directory_id}"
          echo "target_directory_id=${target_directory_id}" >> $GITHUB_OUTPUT

      - id: download_files
        name: Download files (API)
        env:
          access_token: ${{ steps.get_access_token.outputs.access_token }}
          target_directory_id: ${{ steps.get_target_directory_id.outputs.target_directory_id }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          language_directory_list=(
            $(
              curl -s -X GET \
              -H "Authorization:Bearer ${access_token}" \
              "https://api.box.com/2.0/folders/${target_directory_id}/items" | \
              jq -c '.entries[] | {name: .name, id: .id}'
            )
          )
          
          echo "::add-mask::${language_directory_list}"

          for language_directory in "${language_directory_list[@]}"; do
            language=$(echo "${language_directory}" | jq -r ".name")
            language_directory_id=$(echo "${language_directory}" | jq -r ".id")

            string_file_id=$(
              curl -s -X GET \
              -H "Authorization:Bearer ${access_token}" \
              "https://api.box.com/2.0/folders/${language_directory_id}/items" | \
              jq -r ".entries[0].id"
            )
            echo "::add-mask::${string_file_id}"

            cd $WORKSPACE
            if [ "$language" == "en" ]; then
              cd "core/androidCore/src/main/res/values/"
            elif [ "$language" == "zh_TW" ]; then
              cd "core/androidCore/src/main/res/values-zh-rTW/"
            else
              cd "core/androidCore/src/main/res/values-${language}/" 
            fi
          
            curl -L -X GET \
            -H "authorization: Bearer ${access_token}" \
            "https://api.box.com/2.0/files/${string_file_id}/content" > "ma-string.xml"
          
          done

      - name: Set time
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_TIME=$(date +"%Y%m%d_%H")" >> $GITHUB_ENV

      - name: Commit files
        env:
          WORKSPACE: ${{ github.workspace }}
          CURRENT_TIME: ${{ env.CURRENT_TIME }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -b "Update_string_resources"
          git add .
          git commit -m "Update string resources ${CURRENT_TIME}"
          git push -f -u origin "Update_string_resources"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TIME: ${{ env.CURRENT_TIME }}
          BASE_BRANCH: ${{ github.ref_name }}
        run: |
          gh pr create \
            --draft \
            --base "$BASE_BRANCH" \
            --head "Update_string_resources" \
            --title "Update string resources ${CURRENT_TIME}" \
            --body "This PR was automatically created by GitHub Actions to update string resources."
